spring:
 profiles:
  include: native,default
 cloud:
  config:
   discovery:
    enabled: false
   server:
    native:
     searchLocations: d:/noufal/config
    encrypt:
     enabled: true
     
server: 
 port: 8888    
      
  
          
